"""add order delivery information

Revision ID: 0922a6168ffa
Revises: 03166934e21e
Create Date: 2026-09-15 04:33:52.200837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0922a6168ffa'
down_revision: Union[str, Sequence[str], None] = '03166934e21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'orders',
    sa.Column(
        'phone',
        sa.String(length=20),
        nullable=False,
        server_default='N/A'
    )
)
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
